//// GOD GAVE SOME RULES FOR CREATING HUMAN CREATURES LET'S EXPLORE
//// SMALL DISCLAIMER IT'S JUST ONLY FOR LEARNING PURPOSE SO DON'T OVERTHINK GUYS
export class HumanDesign {
}
// let out = new HumanDesign();
